#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2017-2018 Nathan Chancellor

TARGET_VERSION=LA.UM.7.2.r1-05100-sdm660.0
CURRENT_VERSION=LA.UM.7.2.r1-04900-sdm660.0

git remote add qcacld https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/qcacld-3.0
git fetch qcacld

RANGE=821e4be02cd0b2bf77f9af8e0eba68d5ad33bd61..88f803fd797ab3bce735a2a3cd51c44ef170cb03

TAG=${TARGET_VERSION}

function create_merge_message() {
    MSG_FILE=$(mktemp)
    echo "Merge tag ${TARGET_VERSION} into KCUF/drivers/staging/qcacld-3.0" >> "${MSG_FILE}"
    echo "\nChanges in ${TARGET_VERSION}: ($(git rev-list --count "${RANGE}" 2> /dev/null) commits)" >> "${MSG_FILE}"
    git log --reverse --format="        %s" "${RANGE}" >> "${MSG_FILE}"
    echo "\nSigned-off-by: $(git config --get user.name) <$(git config --get user.email)>" >> "${MSG_FILE}"
}

function append_conflicts() {
    echo "\nConflicts:" >> "${MSG_FILE}"
    for FILE in $(git cf); do
        echo "\t${FILE}" >> "${MSG_FILE}"
    done
}

function mg_target_version() {
    header "Merging ${TARGET_VERSION}"

    create_merge_message
    if ! GIT_MERGE_VERBOSITY=1 git subtree pull -q -P drivers/staging/qcacld-3.0 qcacld "${TAG}"; then
#        append_conflicts
        mv "${MSG_FILE}" /tmp/mrg-msg
        die "Merge needs manual intervention! Resolve conflicts then run git fm."
    else
        gpg_available
        git commit --amend --date="$(date)" --file "${MSG_FILE}" --gpg-sign --no-edit --quiet
        rm -f "${MSG_FILE}"
        header "${TARGET_VERSION} MERGED CLEANLY!" "${GRN}"
    fi
}

function update_tree() {
    mg_target_version ;
    exit 0
}

source "$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" || return; pwd)/common"
trap 'echo; die "Manually aborted!"' SIGINT SIGTERM
update_tree
